[versions]
agp = "8.4.0"
kotlin = "1.9.10"
xposed-api = "100"
appcompat = "1.6.1"
compose = "1.6.7"
compose-material3 = "1.2.1"
activity-compose = "1.9.0"

[libraries]
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "xposed-api" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

